### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by innomerphey** [nathaniel-auvil/ogame#1]
sadf

**Comment by lim-bo** [comment]
typo ogamebot*

**Comment by nathaniel-auvil** [comment]
what are you trying to do?

**Comment by lim-bo** [comment]
Intelligent bot for ogame

**Comment by lim-bo** [comment]
But the bot is just a procedure with a lot of conditions. The more conditions are the smarter the bot) the main task is to write api to use most of the game's features. At the moment there are 3 tasks. It's researching, sending fleets and parsing xml files from ogameapi. A lot has already been implemented.

**Comment by nathaniel-auvil** [comment]
bots are illegal according to the game rules

**Comment by lim-bo** [comment]
But we will not use it

**Comment by nathaniel-auvil** [comment]
not interested. thanks.

**Comment by lim-bo** [comment]
Do you play ogame now?

**Comment by nathaniel-auvil** [comment]
yes
